"""
gPTP (IEEE 802.1AS) manager for DS-TT.

Generates ptp4l configuration for transparent clock mode with
hardware timestamping, and manages ptp4l + phc2sys subprocesses.
"""

import logging
import os
import signal
import subprocess
import tempfile
import time

logger = logging.getLogger("ds-tt.gptp")

# ptp4l configuration template for 802.1AS transparent clock
PTP4L_CONFIG_TEMPLATE = """\
# DS-TT ptp4l configuration — IEEE 802.1AS transparent clock
# Auto-generated by DS-TT daemon

[global]
#
# 802.1AS profile settings
#
transportSpecific\t{transport_specific}
domainNumber\t\t{time_domain_number}
network_transport\tL2
delay_mechanism\t\tP2P
time_stamping\t\t{time_stamping}

#
# Transparent clock (TC) mode
# clockType=0x8000 indicates a transparent clock
#
clockType\t\t0x8000

#
# Timing parameters for 802.1AS
#
logAnnounceInterval\t0
logSyncInterval\t\t-3
logMinPdelayReqInterval\t0
announceReceiptTimeout\t3
syncReceiptTimeout\t3

#
# Priority settings
# priority1=255 ensures this TC never becomes GM
#
priority1\t\t{priority1}
priority2\t\t248

#
# Boundary clock parameters (not active in TC mode, but required)
#
boundary_clock_jbod\t1

#
# Servo parameters
#
servo_type\t\tpi
pi_proportional_const\t0.0
pi_integral_const\t0.0
step_threshold\t\t0.00002
first_step_threshold\t0.00002

#
# Logging
#
verbose\t\t\t1
summary_interval\t1
"""

PTP4L_PORT_SECTION = """\

[{interface}]
"""


class GptpManager:
    """Manages ptp4l and phc2sys for 802.1AS transparent clock operation."""

    def __init__(self, config, hw_timestamp_interfaces):
        self.enabled = config.get("enabled", True)
        self.time_domain_number = config.get("time_domain_number", 0)
        self.transport_specific = config.get("transport_specific", 1)
        self.priority1 = config.get("priority1", 255)
        self.hw_interfaces = hw_timestamp_interfaces

        self._ptp4l_proc = None
        self._phc2sys_proc = None
        self._config_path = None
        self._running = False

    def start(self):
        """Start ptp4l and phc2sys."""
        if not self.enabled:
            logger.info("gPTP disabled in config")
            return

        if not self.hw_interfaces:
            logger.warning("No hardware timestamping interfaces — gPTP disabled")
            return

        # Generate ptp4l config
        self._config_path = self._generate_config()
        logger.info("Generated ptp4l config: %s", self._config_path)

        # Start ptp4l
        self._start_ptp4l()

        # Start phc2sys (synchronize PHC to system clock)
        self._start_phc2sys()

        self._running = True

    def _generate_config(self):
        """Generate ptp4l configuration file."""
        # Determine time_stamping mode
        time_stamping = "hardware"
        if not self.hw_interfaces:
            time_stamping = "software"

        config = PTP4L_CONFIG_TEMPLATE.format(
            transport_specific=self.transport_specific,
            time_domain_number=self.time_domain_number,
            time_stamping=time_stamping,
            priority1=self.priority1,
        )

        # Add port sections for each HW timestamp interface
        for iface in self.hw_interfaces:
            config += PTP4L_PORT_SECTION.format(interface=iface)

        # Write to temp file
        fd, path = tempfile.mkstemp(prefix="ds-tt-ptp4l-", suffix=".conf")
        with os.fdopen(fd, "w") as f:
            f.write(config)

        return path

    def _start_ptp4l(self):
        """Start ptp4l process."""
        cmd = [
            "ptp4l",
            "-f", self._config_path,
            "-m",  # print messages to stdout
        ]

        logger.info("Starting ptp4l: %s", " ".join(cmd))
        try:
            self._ptp4l_proc = subprocess.Popen(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
            )
            logger.info("ptp4l started (PID=%d)", self._ptp4l_proc.pid)
        except FileNotFoundError:
            logger.error("ptp4l not found — install linuxptp package")
            raise RuntimeError("ptp4l not found. Install: sudo apt install linuxptp")

    def _start_phc2sys(self):
        """Start phc2sys to sync PHC to system clock."""
        if not self.hw_interfaces:
            return

        primary_iface = self.hw_interfaces[0]
        cmd = [
            "phc2sys",
            "-s", primary_iface,
            "-c", "CLOCK_REALTIME",
            "-O", "0",       # no UTC offset (802.1AS uses TAI-like)
            "-m",            # print messages to stdout
            "-R", "10",      # refresh rate
            "--transportSpecific", str(self.transport_specific),
        ]

        logger.info("Starting phc2sys: %s", " ".join(cmd))
        try:
            self._phc2sys_proc = subprocess.Popen(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
            )
            logger.info("phc2sys started (PID=%d)", self._phc2sys_proc.pid)
        except FileNotFoundError:
            logger.warning("phc2sys not found — PHC sync disabled")

    def stop(self):
        """Stop ptp4l and phc2sys."""
        for name, proc in [("ptp4l", self._ptp4l_proc),
                           ("phc2sys", self._phc2sys_proc)]:
            if proc and proc.poll() is None:
                logger.info("Stopping %s (PID=%d)", name, proc.pid)
                proc.send_signal(signal.SIGTERM)
                try:
                    proc.wait(timeout=5)
                except subprocess.TimeoutExpired:
                    proc.kill()
                    proc.wait()

        self._ptp4l_proc = None
        self._phc2sys_proc = None
        self._running = False

        # Clean up config file
        if self._config_path and os.path.exists(self._config_path):
            os.unlink(self._config_path)
            self._config_path = None

        logger.info("gPTP processes stopped")

    def check_and_restart(self):
        """Check if processes are alive and restart if needed."""
        if not self.enabled or not self._running:
            return

        # Check ptp4l
        if self._ptp4l_proc and self._ptp4l_proc.poll() is not None:
            logger.warning("ptp4l exited (rc=%d) — restarting",
                           self._ptp4l_proc.returncode)
            self._start_ptp4l()

        # Check phc2sys
        if self._phc2sys_proc and self._phc2sys_proc.poll() is not None:
            logger.warning("phc2sys exited (rc=%d) — restarting",
                           self._phc2sys_proc.returncode)
            self._start_phc2sys()

    def get_status(self):
        """Return gPTP status dict for API."""
        status = {
            "enabled": self.enabled,
            "time_domain_number": self.time_domain_number,
            "transport_specific": self.transport_specific,
            "hw_interfaces": self.hw_interfaces,
            "running": self._running,
        }

        if self._ptp4l_proc:
            status["ptp4l"] = {
                "pid": self._ptp4l_proc.pid,
                "alive": self._ptp4l_proc.poll() is None,
            }

        if self._phc2sys_proc:
            status["phc2sys"] = {
                "pid": self._phc2sys_proc.pid,
                "alive": self._phc2sys_proc.poll() is None,
            }

        # Try to read ptp4l clock offset from pmc
        status["clock_info"] = self._read_clock_info()

        return status

    def _read_clock_info(self):
        """Read clock info via pmc (PTP management client)."""
        if not self._running:
            return None

        try:
            result = subprocess.run(
                ["pmc", "-u", "-b", "0",
                 "-t", str(self.transport_specific),
                 "GET CURRENT_DATA_SET"],
                capture_output=True, text=True, timeout=3,
            )
            if result.returncode == 0:
                info = {}
                for line in result.stdout.split("\n"):
                    line = line.strip()
                    if "offsetFromMaster" in line:
                        parts = line.split()
                        if len(parts) >= 2:
                            info["offset_from_master_ns"] = parts[-1]
                    elif "meanPathDelay" in line:
                        parts = line.split()
                        if len(parts) >= 2:
                            info["mean_path_delay_ns"] = parts[-1]
                return info if info else None
        except (FileNotFoundError, subprocess.TimeoutExpired):
            pass
        return None

    def check_health(self):
        """Check if gPTP is healthy."""
        if not self.enabled:
            return True  # Disabled = healthy (not required)
        if not self._running:
            return False
        if self._ptp4l_proc and self._ptp4l_proc.poll() is not None:
            return False
        return True
