const express = require('express');
const { execSync, spawn } = require('child_process');
const fs = require('fs');
const os = require('os');
const path = require('path');
const router = express.Router();

var MAX_LOG_LINES = 100;

/* In-memory state for ptp4l/phc2sys processes */
var ptpState = {
  running: false,
  config: null,
  configPath: null,
  ptp4lProc: null,
  phc2sysProc: null,
  ptp4lPid: null,
  phc2sysPid: null,
  lastLogs: [],
  startedAt: null
};

/*
 * ptp4l configuration template.
 * Ported from tools/ds-tt/ds_tt/gptp.py PTP4L_CONFIG_TEMPLATE.
 */
function generatePtp4lConfig(cfg) {
  var isGptp = cfg.profile === '802.1AS';
  var is1588L2 = cfg.profile === '1588v2-L2';
  var transportSpecific = isGptp ? 1 : 0;
  var networkTransport = (isGptp || is1588L2) ? 'L2' : 'UDPv4';
  var delayMechanism = isGptp ? 'P2P' : 'E2E';
  var domainNumber = cfg.domainNumber != null ? cfg.domainNumber : 0;
  var priority1 = cfg.priority1 != null ? cfg.priority1 : 255;
  var timeStamping = cfg.timeStamping || 'hardware';

  /* Global section modeled on the known-working /etc/ptp.conf */
  var lines = [
    '# ptp4l configuration - generated by Open5GS WebUI',
    '# Profile: ' + cfg.profile,
    '',
    '[global]',
    /* /var/run is not writable for the unprivileged WebUI user */
    'uds_address /tmp/open5gs-ptp4l',
    'priority1 ' + priority1,
    'priority2 128',
    'domainNumber ' + domainNumber,
    'tx_timestamp_timeout 30',
    'dscp_event 46',
    'dscp_general 46',
    'logging_level 6',
    'verbose 1',
    'use_syslog 0',
    'time_stamping ' + timeStamping
  ];

  if (isGptp) {
    lines.push('transportSpecific ' + transportSpecific);
  }

  lines = lines.concat([
    '',
    '[' + cfg.interface + ']',
    'logAnnounceInterval ' + (isGptp ? 0 : 1),
    'announceReceiptTimeout 3',
    'logSyncInterval ' + (isGptp ? -3 : 0),
    isGptp ? 'logMinPdelayReqInterval 0' : 'logMinDelayReqInterval 0',
    'delay_mechanism ' + delayMechanism,
    'network_transport ' + networkTransport,
    ''
  ]);

  return lines.join('\n');
}

/* Validate interface name against OS interfaces to prevent injection.
 * Check /sys/class/net (covers L2-only interfaces without IP addresses)
 * with os.networkInterfaces() as fallback on non-Linux. */
function isValidInterface(name) {
  if (!name || typeof name !== 'string') return false;
  /* Reject anything that isn't a plain interface name */
  if (!/^[a-zA-Z0-9._-]+$/.test(name)) return false;
  try {
    fs.statSync('/sys/class/net/' + name);
    return true;
  } catch (e) {
    /* Fallback for non-Linux */
    var ifaces = os.networkInterfaces();
    return ifaces.hasOwnProperty(name);
  }
}

/* Append line to circular log buffer */
function appendLog(line) {
  ptpState.lastLogs.push(line);
  if (ptpState.lastLogs.length > MAX_LOG_LINES) {
    ptpState.lastLogs.shift();
  }
}

/* Read clock info via pmc (same as tools/ds-tt/ds_tt/gptp.py _read_clock_info) */
function readClockInfo(transportSpecific) {
  try {
    var ts = String(parseInt(transportSpecific, 10) || 1);
    /* pmc binds its local socket under /var/run (hardcoded), so it must
     * run as root: requires a NOPASSWD sudoers entry for pmc. */
    var result = execSync(
      'sudo -n pmc -u -b 0 -t ' + ts +
      " -z /tmp/open5gs-ptp4l 'GET CURRENT_DATA_SET'",
      { timeout: 3000, encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] }
    );
    var info = {};
    var lines = result.split('\n');
    for (var i = 0; i < lines.length; i++) {
      var line = lines[i].trim();
      if (line.indexOf('offsetFromMaster') !== -1) {
        var parts = line.split(/\s+/);
        if (parts.length >= 2) info.offsetFromMasterNs = parts[parts.length - 1];
      } else if (line.indexOf('meanPathDelay') !== -1) {
        var parts2 = line.split(/\s+/);
        if (parts2.length >= 2) info.meanPathDelayNs = parts2[parts2.length - 1];
      }
    }
    return Object.keys(info).length > 0 ? info : null;
  } catch (e) {
    return null;
  }
}

/* ============================================================
 * Readiness + systemd service control
 * Added 2026-10-05.
 *
 * The original /start spawns ptp4l directly from this process. That cannot
 * work here: the WebUI runs as an unprivileged user, and ptp4l needs
 * CAP_NET_RAW, CAP_NET_ADMIN and write access to /dev/ptpN. So PTP is owned
 * by a systemd unit and the WebUI drives that unit through a narrow sudo
 * rule installed by ~/tsntestbed/ptp/setup-ptp.sh.
 *
 * /readiness exists so the page can explain WHY it cannot start rather than
 * failing with a bare permission error.
 * ============================================================ */

var PTP_UNIT = 'ptp4l-tsn.service';
var PHC2SYS_UNIT = 'phc2sys-tsn.service';
var PTP_CONF = '/etc/linuxptp/ptp4l-tsn.conf';

function sh(cmd) {
  try {
    return execSync(cmd, { timeout: 4000, encoding: 'utf-8',
                           stdio: ['pipe', 'pipe', 'pipe'] }).trim();
  } catch (e) {
    return null;
  }
}

/* Every interface that owns a PTP hardware clock, with its link state.
 * Software timestamping is possible without one but is tens of microseconds
 * of jitter, which is not useful for TSN - so the page needs to say plainly
 * which ports are viable. */
function phcPorts() {
  var out = [];
  var names;
  try { names = fs.readdirSync('/sys/class/net'); } catch (e) { return out; }
  names.forEach(function(n) {
    if (n === 'lo') return;
    var t = sh('ethtool -T ' + n);
    if (!t) return;
    var m = /PTP Hardware Clock:\s*(\S+)/.exec(t);
    if (!m || m[1] === 'none') return;
    var carrier = null;
    try {
      carrier = fs.readFileSync('/sys/class/net/' + n + '/carrier', 'utf-8').trim() === '1';
    } catch (e) { /* down interfaces have no carrier file */ }
    var drv = sh('ethtool -i ' + n + " | awk -F': ' '/^driver/{print $2}'");
    out.push({ name: n, phc: parseInt(m[1], 10), carrier: !!carrier, driver: drv || null });
  });
  return out;
}

function unitState(unit) {
  var active = sh('systemctl is-active ' + unit);
  var enabled = sh('systemctl is-enabled ' + unit);
  return {
    unit: unit,
    /* is-active exits non-zero when inactive, so sh() returns null - that is
     * "inactive", not "unknown". Only a missing unit file is unknown. */
    exists: enabled !== null || active !== null,
    active: active === 'active',
    enabled: enabled === 'enabled',
    state: active || 'inactive'
  };
}

/* The four values that must match the grandmaster exactly. A mismatch is
 * silent - ptp4l never leaves s0 - so the page shows them rather than making
 * anyone open a file on the server to find out what is configured. */
function activeConfig() {
  var txt;
  try { txt = fs.readFileSync(PTP_CONF, 'utf-8'); } catch (e) { return null; }
  function val(key) {
    var m = new RegExp('^\\s*' + key + '\\s+(\\S+)', 'm').exec(txt);
    return m ? m[1] : null;
  }
  /* the bound interface is the lone [section] after [global] */
  var iface = null;
  var secs = txt.match(/^\[([^\]]+)\]/gm) || [];
  secs.forEach(function(x) {
    var n = x.replace(/[\[\]]/g, '');
    if (n !== 'global') iface = n;
  });
  var ts = val('transportSpecific');
  return {
    path: PTP_CONF,
    interface: iface,
    domain: val('domainNumber'),
    transport: val('network_transport'),
    delay_mechanism: val('delay_mechanism'),
    time_stamping: val('time_stamping'),
    transportSpecific: ts,
    /* 802.1AS is the only profile that sets transportSpecific to 1 */
    profile: (ts === '0x1' || ts === '1') ? '802.1AS' : 'IEEE 1588',
    vlan: iface && /\.(\d+)$/.test(iface) ? iface.replace(/^.*\.(\d+)$/, '$1') : null
  };
}

/* GET /api/ptp/readiness */
router.get('/readiness', function(req, res) {
  var installed = !!sh('command -v ptp4l');
  var ports = phcPorts();
  var usable = ports.filter(function(p) { return p.carrier; });
  var unit = unitState(PTP_UNIT);
  var phc2sys = unitState(PHC2SYS_UNIT);
  /* -n never prompts, so this succeeds only if a NOPASSWD rule covers it.
   * It must be a command the rule actually GRANTS: `is-enabled` is not in the
   * rule, so probing with that reported "not permitted" even when control was
   * working. `show --property=Id` is granted, read-only and side-effect free. */
  var canControl = sh('sudo -n systemctl show ' + PTP_UNIT +
                      ' --property=Id 2>/dev/null') !== null;

  var checks = [
    { id: 'linuxptp', ok: installed,
      label: 'linuxptp installed',
      detail: installed ? (sh('ptp4l -v 2>&1 | head -1') || 'present')
                        : 'ptp4l not found' },
    { id: 'hwclock', ok: ports.length > 0,
      label: 'network port with a PTP hardware clock',
      detail: ports.length
        ? ports.map(function(p) {
            return p.name + ' (' + p.driver + ', /dev/ptp' + p.phc + ', link ' +
                   (p.carrier ? 'up' : 'down') + ')';
          }).join('; ')
        : 'no port reports a PHC - the Broadcom bnxt_en ports need a niccli NVM change' },
    { id: 'link', ok: usable.length > 0,
      label: 'that port is cabled and up',
      detail: usable.length ? usable.map(function(p) { return p.name; }).join(', ')
                            : 'a PHC-capable port exists but has no carrier' },
    { id: 'unit', ok: unit.exists,
      label: 'ptp4l systemd unit installed',
      detail: unit.exists ? unit.unit + ' (' + unit.state + ')' : 'not installed' },
    { id: 'control', ok: canControl,
      label: 'WebUI permitted to start/stop it',
      detail: canControl ? 'sudoers rule present'
                         : 'missing /etc/sudoers.d/open5gs-webui-ptp' }
  ];

  var ready = checks.every(function(c) { return c.ok; });

  res.json({
    ready: ready,
    checks: checks,
    ports: ports,
    service: unit,
    phc2sys: phc2sys,
    /* The one command that fixes every failing check above. */
    config: activeConfig(),
    fixCommand: 'sudo /home/tsn_server/tsntestbed/ptp/setup-ptp.sh',
    /* Detection needs tcpdump, which is deliberately NOT in the sudoers rule:
     * granting it would let the WebUI read arbitrary traffic on any interface.
     * The operator runs this one by hand. */
    detectCommand: 'sudo /home/tsn_server/tsntestbed/ptp/setup-ptp.sh --detect-only'
  });
});

/* GET /api/ptp/service - live state plus recent journal */
router.get('/service', function(req, res) {
  var unit = unitState(PTP_UNIT);
  var logs = sh('journalctl -u ' + PTP_UNIT + ' -n 40 --no-pager -o short-iso');
  var offset = null, portState = null;
  if (logs) {
    /* ptp4l -m prints e.g. "master offset -42 s2 freq ..." - s2 is locked. */
    var lines = logs.split('\n');
    for (var i = lines.length - 1; i >= 0; i--) {
      var m = /master offset\s+(-?\d+)\s+s(\d)/.exec(lines[i]);
      if (m) { offset = parseInt(m[1], 10); portState = 's' + m[2]; break; }
    }
  }
  res.json({
    service: unit,
    phc2sys: unitState(PHC2SYS_UNIT),
    config: activeConfig(),
    offset_ns: offset,
    /* s0 unlocked, s1 acquiring, s2 locked */
    sync_state: portState,
    locked: portState === 's2',
    logs: logs ? logs.split('\n').slice(-25) : []
  });
});

/* POST /api/ptp/service { action: start|stop|restart, unit: ptp4l|phc2sys } */
router.post('/service', function(req, res) {
  var b = req.body || {};
  var action = String(b.action || '');
  if (['start', 'stop', 'restart'].indexOf(action) === -1) {
    return res.status(400).json({ message: 'action must be start, stop or restart' });
  }
  var unit = b.unit === 'phc2sys' ? PHC2SYS_UNIT : PTP_UNIT;
  if (unit === PHC2SYS_UNIT && action === 'restart') {
    return res.status(400).json({ message: 'phc2sys supports start and stop only' });
  }

  var out = sh('sudo -n systemctl ' + action + ' ' + unit + ' 2>&1');
  if (out === null) {
    return res.status(403).json({
      message: 'Not permitted to ' + action + ' ' + unit + '. Run: ' +
               'sudo /home/tsn_server/tsntestbed/ptp/setup-ptp.sh'
    });
  }
  /* Give the daemon a moment to settle so the caller gets a true state. */
  setTimeout(function() {
    res.json({ ok: true, action: action, unit: unit, state: unitState(unit) });
  }, 1200);
});

/* GET /api/ptp/status */
router.get('/status', function(req, res) {
  var result = {
    running: ptpState.running,
    config: ptpState.config,
    startedAt: ptpState.startedAt,
    lastLogs: ptpState.lastLogs.slice(-20)
  };

  if (ptpState.ptp4lProc) {
    result.ptp4l = {
      pid: ptpState.ptp4lPid,
      alive: ptpState.ptp4lProc.exitCode === null
    };
  }

  if (ptpState.phc2sysProc) {
    result.phc2sys = {
      pid: ptpState.phc2sysPid,
      alive: ptpState.phc2sysProc.exitCode === null
    };
  }

  /* Read clock info if running */
  if (ptpState.running && ptpState.config) {
    var ts = ptpState.config.profile === '802.1AS' ? 1 : 0;
    result.clockInfo = readClockInfo(ts);
  }

  res.json(result);
});

/* GET /api/ptp/interfaces
 *
 * Uses /sys/class/net to enumerate ALL network interfaces, not just those
 * with IP addresses.  os.networkInterfaces() only returns interfaces that
 * have an IP assigned, which excludes pure L2 interfaces (typical for TSN
 * Ethernet ports used with PTP).
 */
router.get('/interfaces', function(req, res) {
  var result = [];
  var names;

  try {
    names = fs.readdirSync('/sys/class/net');
  } catch (e) {
    /* Fallback to os.networkInterfaces() on non-Linux */
    names = Object.keys(os.networkInterfaces());
  }

  names.forEach(function(name) {
    if (name === 'lo') return;

    /* Read MAC from sysfs (works even without an IP address) */
    var mac = '';
    try {
      mac = fs.readFileSync('/sys/class/net/' + name + '/address', 'utf-8')
              .trim();
    } catch (e) {
      /* If sysfs read fails, try os.networkInterfaces() */
      var osIfaces = os.networkInterfaces();
      if (osIfaces[name]) {
        for (var i = 0; i < osIfaces[name].length; i++) {
          if (osIfaces[name][i].mac &&
              osIfaces[name][i].mac !== '00:00:00:00:00:00') {
            mac = osIfaces[name][i].mac;
            break;
          }
        }
      }
    }

    /* Skip virtual/loopback-like interfaces with no real MAC */
    if (mac === '00:00:00:00:00:00') return;

    var entry = {
      name: name,
      mac: mac,
      hwTimestamp: false,
      capabilities: []
    };

    /* Detect HW timestamping via ethtool -T */
    try {
      var output = execSync('ethtool -T ' + name,
        { timeout: 3000, encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] });
      var lines = output.split('\n');
      for (var j = 0; j < lines.length; j++) {
        var line = lines[j].trim();
        if (line.indexOf('hardware-transmit') !== -1) {
          entry.capabilities.push('hardware-transmit');
        }
        if (line.indexOf('hardware-receive') !== -1) {
          entry.capabilities.push('hardware-receive');
        }
        if (line.indexOf('hardware-raw-clock') !== -1) {
          entry.capabilities.push('hardware-raw-clock');
        }
        if (line.indexOf('software-transmit') !== -1) {
          entry.capabilities.push('software-transmit');
        }
        if (line.indexOf('software-receive') !== -1) {
          entry.capabilities.push('software-receive');
        }
      }
      if (entry.capabilities.indexOf('hardware-transmit') !== -1 &&
          entry.capabilities.indexOf('hardware-receive') !== -1) {
        entry.hwTimestamp = true;
      }
    } catch (e) {
      /* ethtool may not be installed or interface may not support it */
    }

    result.push(entry);
  });

  res.json(result);
});

/* POST /api/ptp/config */
router.post('/config', function(req, res) {
  var cfg = req.body;

  if (!cfg || !cfg.profile || !cfg.interface) {
    return res.status(400).json({ message: 'profile and interface are required' });
  }

  if (cfg.profile !== '802.1AS' && cfg.profile !== '1588v2-L2' &&
      cfg.profile !== '1588v2') {
    return res.status(400).json({
      message: 'profile must be "802.1AS", "1588v2-L2", or "1588v2"'
    });
  }

  if (!isValidInterface(cfg.interface)) {
    return res.status(400).json({
      message: 'Invalid interface: ' + cfg.interface
    });
  }

  if (cfg.domainNumber != null) {
    cfg.domainNumber = parseInt(cfg.domainNumber, 10);
    if (isNaN(cfg.domainNumber) || cfg.domainNumber < 0 || cfg.domainNumber > 127) {
      return res.status(400).json({ message: 'domainNumber must be 0-127' });
    }
  }

  if (cfg.priority1 != null) {
    cfg.priority1 = parseInt(cfg.priority1, 10);
    if (isNaN(cfg.priority1) || cfg.priority1 < 0 || cfg.priority1 > 255) {
      return res.status(400).json({ message: 'priority1 must be 0-255' });
    }
  }

  ptpState.config = {
    profile: cfg.profile,
    interface: cfg.interface,
    domainNumber: cfg.domainNumber || 0,
    priority1: cfg.priority1 != null ? cfg.priority1 : 255,
    timeStamping: cfg.timeStamping === 'software' ? 'software' : 'hardware'
  };

  res.json({ saved: true, config: ptpState.config });
});

/* POST /api/ptp/start */
router.post('/start', function(req, res) {
  if (ptpState.running) {
    return res.status(409).json({ message: 'PTP is already running' });
  }

  if (!ptpState.config) {
    return res.status(400).json({
      message: 'No configuration saved. POST /api/ptp/config first.'
    });
  }

  var cfg = ptpState.config;

  /* Re-validate interface */
  if (!isValidInterface(cfg.interface)) {
    return res.status(400).json({
      message: 'Interface ' + cfg.interface + ' no longer exists'
    });
  }

  /* Generate config file */
  var configContent = generatePtp4lConfig(cfg);
  var tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'open5gs-ptp-'));
  var configPath = path.join(tmpDir, 'ptp4l.conf');
  fs.writeFileSync(configPath, configContent);
  ptpState.configPath = configPath;
  ptpState.lastLogs = [];

  appendLog('[WebUI] Generated ptp4l config: ' + configPath);
  appendLog('[WebUI] Profile: ' + cfg.profile + ', Interface: ' + cfg.interface);

  /* Start ptp4l */
  try {
    var ptp4lArgs = ['-f', configPath, '-m'];
    var ptp4lProc = spawn('ptp4l', ptp4lArgs, {
      stdio: ['pipe', 'pipe', 'pipe']
    });
    ptpState.ptp4lProc = ptp4lProc;
    ptpState.ptp4lPid = ptp4lProc.pid;
    appendLog('[WebUI] ptp4l started (PID=' + ptp4lProc.pid + ')');

    ptp4lProc.stdout.on('data', function(data) {
      var lines = data.toString().split('\n');
      for (var i = 0; i < lines.length; i++) {
        if (lines[i].trim()) appendLog('[ptp4l] ' + lines[i]);
      }
    });
    ptp4lProc.stderr.on('data', function(data) {
      var lines = data.toString().split('\n');
      for (var i = 0; i < lines.length; i++) {
        if (lines[i].trim()) appendLog('[ptp4l:err] ' + lines[i]);
      }
    });
    ptp4lProc.on('exit', function(code) {
      appendLog('[WebUI] ptp4l exited (code=' + code + ')');
    });
  } catch (e) {
    return res.status(500).json({
      message: 'Failed to start ptp4l: ' + e.message +
        '. Ensure linuxptp is installed (sudo apt install linuxptp).'
    });
  }

  /* Start phc2sys only when explicitly requested. Syncing CLOCK_REALTIME
   * to a GM with an arbitrary epoch can step the system clock years away
   * (breaking TLS certs, NTP, MongoDB TTL). TSN only needs the PHC sync
   * that ptp4l provides. */
  if (cfg.syncSystemClock) {
  try {
    var ts = cfg.profile === '802.1AS' ? '1' : '0';
    var phc2sysArgs = [
      '-s', cfg.interface,
      '-c', 'CLOCK_REALTIME',
      '-O', '0',
      /* Step the clock for offsets > 1s instead of slewing forever;
       * a GM with an arbitrary epoch can be years away from system time.
       * Requires NTP (systemd-timesyncd/chrony) to be disabled. */
      '-S', '1',
      '-m',
      '-R', '10',
      '--transportSpecific', ts
    ];
    var phc2sysProc = spawn('phc2sys', phc2sysArgs, {
      stdio: ['pipe', 'pipe', 'pipe']
    });
    ptpState.phc2sysProc = phc2sysProc;
    ptpState.phc2sysPid = phc2sysProc.pid;
    appendLog('[WebUI] phc2sys started (PID=' + phc2sysProc.pid + ')');

    phc2sysProc.stdout.on('data', function(data) {
      var lines = data.toString().split('\n');
      for (var i = 0; i < lines.length; i++) {
        if (lines[i].trim()) appendLog('[phc2sys] ' + lines[i]);
      }
    });
    phc2sysProc.stderr.on('data', function(data) {
      var lines = data.toString().split('\n');
      for (var i = 0; i < lines.length; i++) {
        if (lines[i].trim()) appendLog('[phc2sys:err] ' + lines[i]);
      }
    });
    phc2sysProc.on('exit', function(code) {
      appendLog('[WebUI] phc2sys exited (code=' + code + ')');
    });
  } catch (e) {
    appendLog('[WebUI] phc2sys not found — PHC sync disabled');
  }
  } else {
    appendLog('[WebUI] phc2sys skipped (system clock sync disabled)');
  }

  ptpState.running = true;
  ptpState.startedAt = Date.now();

  res.json({
    started: true,
    ptp4l: { pid: ptpState.ptp4lPid },
    phc2sys: { pid: ptpState.phc2sysPid }
  });
});

/* POST /api/ptp/stop */
router.post('/stop', function(req, res) {
  if (!ptpState.running) {
    return res.status(409).json({ message: 'PTP is not running' });
  }

  var procs = [
    { name: 'ptp4l', proc: ptpState.ptp4lProc },
    { name: 'phc2sys', proc: ptpState.phc2sysProc }
  ];

  procs.forEach(function(p) {
    if (p.proc && p.proc.exitCode === null) {
      appendLog('[WebUI] Stopping ' + p.name + ' (PID=' + p.proc.pid + ')');
      p.proc.kill('SIGTERM');
      /* Force kill after 5 seconds if still alive */
      setTimeout(function() {
        try {
          if (p.proc.exitCode === null) {
            p.proc.kill('SIGKILL');
          }
        } catch (e) { /* ignore */ }
      }, 5000);
    }
  });

  /* Clean up config file */
  if (ptpState.configPath) {
    try {
      fs.unlinkSync(ptpState.configPath);
      var dir = path.dirname(ptpState.configPath);
      fs.rmdirSync(dir);
    } catch (e) { /* ignore */ }
    ptpState.configPath = null;
  }

  ptpState.ptp4lProc = null;
  ptpState.phc2sysProc = null;
  ptpState.ptp4lPid = null;
  ptpState.phc2sysPid = null;
  ptpState.running = false;
  ptpState.startedAt = null;

  appendLog('[WebUI] PTP processes stopped');

  res.json({ stopped: true });
});

/* Clean up on server shutdown */
process.on('SIGTERM', function() {
  if (ptpState.ptp4lProc && ptpState.ptp4lProc.exitCode === null) {
    ptpState.ptp4lProc.kill('SIGTERM');
  }
  if (ptpState.phc2sysProc && ptpState.phc2sysProc.exitCode === null) {
    ptpState.phc2sysProc.kill('SIGTERM');
  }
});

module.exports = router;
