const express = require('express');
const { execSync, spawn } = require('child_process');
const fs = require('fs');
const os = require('os');
const path = require('path');
const router = express.Router();

var MAX_LOG_LINES = 100;

/* In-memory state for ptp4l/phc2sys processes */
var ptpState = {
  running: false,
  config: null,
  configPath: null,
  ptp4lProc: null,
  phc2sysProc: null,
  ptp4lPid: null,
  phc2sysPid: null,
  lastLogs: [],
  startedAt: null
};

/*
 * ptp4l configuration template.
 * Ported from tools/ds-tt/ds_tt/gptp.py PTP4L_CONFIG_TEMPLATE.
 */
function generatePtp4lConfig(cfg) {
  var isGptp = cfg.profile === '802.1AS';
  var is1588L2 = cfg.profile === '1588v2-L2';
  var transportSpecific = isGptp ? 1 : 0;
  var networkTransport = (isGptp || is1588L2) ? 'L2' : 'UDPv4';
  var delayMechanism = isGptp ? 'P2P' : 'E2E';
  var domainNumber = cfg.domainNumber != null ? cfg.domainNumber : 0;
  var priority1 = cfg.priority1 != null ? cfg.priority1 : 255;
  var timeStamping = cfg.timeStamping || 'hardware';

  /* Global section modeled on the known-working /etc/ptp.conf */
  var lines = [
    '# ptp4l configuration - generated by Open5GS WebUI',
    '# Profile: ' + cfg.profile,
    '',
    '[global]',
    /* /var/run is not writable for the unprivileged WebUI user */
    'uds_address /tmp/open5gs-ptp4l',
    'priority1 ' + priority1,
    'priority2 128',
    'domainNumber ' + domainNumber,
    'tx_timestamp_timeout 30',
    'dscp_event 46',
    'dscp_general 46',
    'logging_level 6',
    'verbose 1',
    'use_syslog 0',
    'time_stamping ' + timeStamping
  ];

  if (isGptp) {
    lines.push('transportSpecific ' + transportSpecific);
  }

  lines = lines.concat([
    '',
    '[' + cfg.interface + ']',
    'logAnnounceInterval ' + (isGptp ? 0 : 1),
    'announceReceiptTimeout 3',
    'logSyncInterval ' + (isGptp ? -3 : 0),
    isGptp ? 'logMinPdelayReqInterval 0' : 'logMinDelayReqInterval 0',
    'delay_mechanism ' + delayMechanism,
    'network_transport ' + networkTransport,
    ''
  ]);

  return lines.join('\n');
}

/* Validate interface name against OS interfaces to prevent injection.
 * Check /sys/class/net (covers L2-only interfaces without IP addresses)
 * with os.networkInterfaces() as fallback on non-Linux. */
function isValidInterface(name) {
  if (!name || typeof name !== 'string') return false;
  /* Reject anything that isn't a plain interface name */
  if (!/^[a-zA-Z0-9._-]+$/.test(name)) return false;
  try {
    fs.statSync('/sys/class/net/' + name);
    return true;
  } catch (e) {
    /* Fallback for non-Linux */
    var ifaces = os.networkInterfaces();
    return ifaces.hasOwnProperty(name);
  }
}

/* Append line to circular log buffer */
function appendLog(line) {
  ptpState.lastLogs.push(line);
  if (ptpState.lastLogs.length > MAX_LOG_LINES) {
    ptpState.lastLogs.shift();
  }
}

/* Read clock info via pmc (same as tools/ds-tt/ds_tt/gptp.py _read_clock_info) */
function readClockInfo(transportSpecific) {
  try {
    var ts = String(parseInt(transportSpecific, 10) || 1);
    /* pmc binds its local socket under /var/run (hardcoded), so it must
     * run as root: requires a NOPASSWD sudoers entry for pmc. */
    var result = execSync(
      'sudo -n pmc -u -b 0 -t ' + ts +
      " -z /tmp/open5gs-ptp4l 'GET CURRENT_DATA_SET'",
      { timeout: 3000, encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] }
    );
    var info = {};
    var lines = result.split('\n');
    for (var i = 0; i < lines.length; i++) {
      var line = lines[i].trim();
      if (line.indexOf('offsetFromMaster') !== -1) {
        var parts = line.split(/\s+/);
        if (parts.length >= 2) info.offsetFromMasterNs = parts[parts.length - 1];
      } else if (line.indexOf('meanPathDelay') !== -1) {
        var parts2 = line.split(/\s+/);
        if (parts2.length >= 2) info.meanPathDelayNs = parts2[parts2.length - 1];
      }
    }
    return Object.keys(info).length > 0 ? info : null;
  } catch (e) {
    return null;
  }
}

/* GET /api/ptp/status */
router.get('/status', function(req, res) {
  var result = {
    running: ptpState.running,
    config: ptpState.config,
    startedAt: ptpState.startedAt,
    lastLogs: ptpState.lastLogs.slice(-20)
  };

  if (ptpState.ptp4lProc) {
    result.ptp4l = {
      pid: ptpState.ptp4lPid,
      alive: ptpState.ptp4lProc.exitCode === null
    };
  }

  if (ptpState.phc2sysProc) {
    result.phc2sys = {
      pid: ptpState.phc2sysPid,
      alive: ptpState.phc2sysProc.exitCode === null
    };
  }

  /* Read clock info if running */
  if (ptpState.running && ptpState.config) {
    var ts = ptpState.config.profile === '802.1AS' ? 1 : 0;
    result.clockInfo = readClockInfo(ts);
  }

  res.json(result);
});

/* GET /api/ptp/interfaces
 *
 * Uses /sys/class/net to enumerate ALL network interfaces, not just those
 * with IP addresses.  os.networkInterfaces() only returns interfaces that
 * have an IP assigned, which excludes pure L2 interfaces (typical for TSN
 * Ethernet ports used with PTP).
 */
router.get('/interfaces', function(req, res) {
  var result = [];
  var names;

  try {
    names = fs.readdirSync('/sys/class/net');
  } catch (e) {
    /* Fallback to os.networkInterfaces() on non-Linux */
    names = Object.keys(os.networkInterfaces());
  }

  names.forEach(function(name) {
    if (name === 'lo') return;

    /* Read MAC from sysfs (works even without an IP address) */
    var mac = '';
    try {
      mac = fs.readFileSync('/sys/class/net/' + name + '/address', 'utf-8')
              .trim();
    } catch (e) {
      /* If sysfs read fails, try os.networkInterfaces() */
      var osIfaces = os.networkInterfaces();
      if (osIfaces[name]) {
        for (var i = 0; i < osIfaces[name].length; i++) {
          if (osIfaces[name][i].mac &&
              osIfaces[name][i].mac !== '00:00:00:00:00:00') {
            mac = osIfaces[name][i].mac;
            break;
          }
        }
      }
    }

    /* Skip virtual/loopback-like interfaces with no real MAC */
    if (mac === '00:00:00:00:00:00') return;

    var entry = {
      name: name,
      mac: mac,
      hwTimestamp: false,
      capabilities: []
    };

    /* Detect HW timestamping via ethtool -T */
    try {
      var output = execSync('ethtool -T ' + name,
        { timeout: 3000, encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] });
      var lines = output.split('\n');
      for (var j = 0; j < lines.length; j++) {
        var line = lines[j].trim();
        if (line.indexOf('hardware-transmit') !== -1) {
          entry.capabilities.push('hardware-transmit');
        }
        if (line.indexOf('hardware-receive') !== -1) {
          entry.capabilities.push('hardware-receive');
        }
        if (line.indexOf('hardware-raw-clock') !== -1) {
          entry.capabilities.push('hardware-raw-clock');
        }
        if (line.indexOf('software-transmit') !== -1) {
          entry.capabilities.push('software-transmit');
        }
        if (line.indexOf('software-receive') !== -1) {
          entry.capabilities.push('software-receive');
        }
      }
      if (entry.capabilities.indexOf('hardware-transmit') !== -1 &&
          entry.capabilities.indexOf('hardware-receive') !== -1) {
        entry.hwTimestamp = true;
      }
    } catch (e) {
      /* ethtool may not be installed or interface may not support it */
    }

    result.push(entry);
  });

  res.json(result);
});

/* POST /api/ptp/config */
router.post('/config', function(req, res) {
  var cfg = req.body;

  if (!cfg || !cfg.profile || !cfg.interface) {
    return res.status(400).json({ message: 'profile and interface are required' });
  }

  if (cfg.profile !== '802.1AS' && cfg.profile !== '1588v2-L2' &&
      cfg.profile !== '1588v2') {
    return res.status(400).json({
      message: 'profile must be "802.1AS", "1588v2-L2", or "1588v2"'
    });
  }

  if (!isValidInterface(cfg.interface)) {
    return res.status(400).json({
      message: 'Invalid interface: ' + cfg.interface
    });
  }

  if (cfg.domainNumber != null) {
    cfg.domainNumber = parseInt(cfg.domainNumber, 10);
    if (isNaN(cfg.domainNumber) || cfg.domainNumber < 0 || cfg.domainNumber > 127) {
      return res.status(400).json({ message: 'domainNumber must be 0-127' });
    }
  }

  if (cfg.priority1 != null) {
    cfg.priority1 = parseInt(cfg.priority1, 10);
    if (isNaN(cfg.priority1) || cfg.priority1 < 0 || cfg.priority1 > 255) {
      return res.status(400).json({ message: 'priority1 must be 0-255' });
    }
  }

  ptpState.config = {
    profile: cfg.profile,
    interface: cfg.interface,
    domainNumber: cfg.domainNumber || 0,
    priority1: cfg.priority1 != null ? cfg.priority1 : 255,
    timeStamping: cfg.timeStamping === 'software' ? 'software' : 'hardware'
  };

  res.json({ saved: true, config: ptpState.config });
});

/* POST /api/ptp/start */
router.post('/start', function(req, res) {
  if (ptpState.running) {
    return res.status(409).json({ message: 'PTP is already running' });
  }

  if (!ptpState.config) {
    return res.status(400).json({
      message: 'No configuration saved. POST /api/ptp/config first.'
    });
  }

  var cfg = ptpState.config;

  /* Re-validate interface */
  if (!isValidInterface(cfg.interface)) {
    return res.status(400).json({
      message: 'Interface ' + cfg.interface + ' no longer exists'
    });
  }

  /* Generate config file */
  var configContent = generatePtp4lConfig(cfg);
  var tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'open5gs-ptp-'));
  var configPath = path.join(tmpDir, 'ptp4l.conf');
  fs.writeFileSync(configPath, configContent);
  ptpState.configPath = configPath;
  ptpState.lastLogs = [];

  appendLog('[WebUI] Generated ptp4l config: ' + configPath);
  appendLog('[WebUI] Profile: ' + cfg.profile + ', Interface: ' + cfg.interface);

  /* Start ptp4l */
  try {
    var ptp4lArgs = ['-f', configPath, '-m'];
    var ptp4lProc = spawn('ptp4l', ptp4lArgs, {
      stdio: ['pipe', 'pipe', 'pipe']
    });
    ptpState.ptp4lProc = ptp4lProc;
    ptpState.ptp4lPid = ptp4lProc.pid;
    appendLog('[WebUI] ptp4l started (PID=' + ptp4lProc.pid + ')');

    ptp4lProc.stdout.on('data', function(data) {
      var lines = data.toString().split('\n');
      for (var i = 0; i < lines.length; i++) {
        if (lines[i].trim()) appendLog('[ptp4l] ' + lines[i]);
      }
    });
    ptp4lProc.stderr.on('data', function(data) {
      var lines = data.toString().split('\n');
      for (var i = 0; i < lines.length; i++) {
        if (lines[i].trim()) appendLog('[ptp4l:err] ' + lines[i]);
      }
    });
    ptp4lProc.on('exit', function(code) {
      appendLog('[WebUI] ptp4l exited (code=' + code + ')');
    });
  } catch (e) {
    return res.status(500).json({
      message: 'Failed to start ptp4l: ' + e.message +
        '. Ensure linuxptp is installed (sudo apt install linuxptp).'
    });
  }

  /* Start phc2sys only when explicitly requested. Syncing CLOCK_REALTIME
   * to a GM with an arbitrary epoch can step the system clock years away
   * (breaking TLS certs, NTP, MongoDB TTL). TSN only needs the PHC sync
   * that ptp4l provides. */
  if (cfg.syncSystemClock) {
  try {
    var ts = cfg.profile === '802.1AS' ? '1' : '0';
    var phc2sysArgs = [
      '-s', cfg.interface,
      '-c', 'CLOCK_REALTIME',
      '-O', '0',
      /* Step the clock for offsets > 1s instead of slewing forever;
       * a GM with an arbitrary epoch can be years away from system time.
       * Requires NTP (systemd-timesyncd/chrony) to be disabled. */
      '-S', '1',
      '-m',
      '-R', '10',
      '--transportSpecific', ts
    ];
    var phc2sysProc = spawn('phc2sys', phc2sysArgs, {
      stdio: ['pipe', 'pipe', 'pipe']
    });
    ptpState.phc2sysProc = phc2sysProc;
    ptpState.phc2sysPid = phc2sysProc.pid;
    appendLog('[WebUI] phc2sys started (PID=' + phc2sysProc.pid + ')');

    phc2sysProc.stdout.on('data', function(data) {
      var lines = data.toString().split('\n');
      for (var i = 0; i < lines.length; i++) {
        if (lines[i].trim()) appendLog('[phc2sys] ' + lines[i]);
      }
    });
    phc2sysProc.stderr.on('data', function(data) {
      var lines = data.toString().split('\n');
      for (var i = 0; i < lines.length; i++) {
        if (lines[i].trim()) appendLog('[phc2sys:err] ' + lines[i]);
      }
    });
    phc2sysProc.on('exit', function(code) {
      appendLog('[WebUI] phc2sys exited (code=' + code + ')');
    });
  } catch (e) {
    appendLog('[WebUI] phc2sys not found — PHC sync disabled');
  }
  } else {
    appendLog('[WebUI] phc2sys skipped (system clock sync disabled)');
  }

  ptpState.running = true;
  ptpState.startedAt = Date.now();

  res.json({
    started: true,
    ptp4l: { pid: ptpState.ptp4lPid },
    phc2sys: { pid: ptpState.phc2sysPid }
  });
});

/* POST /api/ptp/stop */
router.post('/stop', function(req, res) {
  if (!ptpState.running) {
    return res.status(409).json({ message: 'PTP is not running' });
  }

  var procs = [
    { name: 'ptp4l', proc: ptpState.ptp4lProc },
    { name: 'phc2sys', proc: ptpState.phc2sysProc }
  ];

  procs.forEach(function(p) {
    if (p.proc && p.proc.exitCode === null) {
      appendLog('[WebUI] Stopping ' + p.name + ' (PID=' + p.proc.pid + ')');
      p.proc.kill('SIGTERM');
      /* Force kill after 5 seconds if still alive */
      setTimeout(function() {
        try {
          if (p.proc.exitCode === null) {
            p.proc.kill('SIGKILL');
          }
        } catch (e) { /* ignore */ }
      }, 5000);
    }
  });

  /* Clean up config file */
  if (ptpState.configPath) {
    try {
      fs.unlinkSync(ptpState.configPath);
      var dir = path.dirname(ptpState.configPath);
      fs.rmdirSync(dir);
    } catch (e) { /* ignore */ }
    ptpState.configPath = null;
  }

  ptpState.ptp4lProc = null;
  ptpState.phc2sysProc = null;
  ptpState.ptp4lPid = null;
  ptpState.phc2sysPid = null;
  ptpState.running = false;
  ptpState.startedAt = null;

  appendLog('[WebUI] PTP processes stopped');

  res.json({ stopped: true });
});

/* Clean up on server shutdown */
process.on('SIGTERM', function() {
  if (ptpState.ptp4lProc && ptpState.ptp4lProc.exitCode === null) {
    ptpState.ptp4lProc.kill('SIGTERM');
  }
  if (ptpState.phc2sysProc && ptpState.phc2sysProc.exitCode === null) {
    ptpState.phc2sysProc.kill('SIGTERM');
  }
});

module.exports = router;
